"""
LastAgent Init Command

Installation wizard that guides users through setup:
- API key configuration
- Default agent selection
- Configuration file creation
"""

import os
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

from cli.tui.console import (
    console,
    print_logo,
    print_success,
    print_warning,
    print_error,
    print_info,
)


# ============================================================================
# Configuration
# ============================================================================

CONFIG_DIR = Path.home() / ".lastagent"
CONFIG_FILE = CONFIG_DIR / "config.yml"

SUPPORTED_AGENTS = {
    "claude": {
        "name": "Claude",
        "env_var": "ANTHROPIC_API_KEY",
        "url": "https://console.anthropic.com/settings/keys",
        "test_cmd": ["claude", "--version"],
    },
    "gemini": {
        "name": "Gemini", 
        "env_var": "GEMINI_API_KEY",
        "url": "https://aistudio.google.com/app/apikey",
        "test_cmd": ["gemini", "--version"],
    },
    "aider": {
        "name": "Aider",
        "env_var": "OPENAI_API_KEY",  # or ANTHROPIC_API_KEY
        "url": "https://aider.chat/docs/install.html",
        "test_cmd": ["aider", "--version"],
    },
    "codex": {
        "name": "Codex",
        "env_var": "OPENAI_API_KEY",
        "url": "https://platform.openai.com/api-keys",
        "test_cmd": ["codex", "--version"],
    },
    "goose": {
        "name": "Goose",
        "env_var": None,  # Uses its own config
        "url": "https://github.com/block/goose",
        "test_cmd": ["goose", "--version"],
    },
}


# ============================================================================
# Helper Functions
# ============================================================================

def check_cli_installed(agent: str) -> bool:
    """Check if an agent CLI is installed."""
    import shutil
    cmd = SUPPORTED_AGENTS.get(agent, {}).get("test_cmd", [agent])
    return shutil.which(cmd[0]) is not None


def check_api_key(agent: str) -> Optional[str]:
    """Check if API key is set for an agent."""
    env_var = SUPPORTED_AGENTS.get(agent, {}).get("env_var")
    if env_var:
        return os.environ.get(env_var)
    return None


def write_config(config: dict) -> bool:
    """Write configuration to YAML file."""
    try:
        CONFIG_DIR.mkdir(exist_ok=True)
        
        # Simple YAML writing without external dependency
        lines = ["# LastAgent Configuration", "# Generated by 'lastagent init'", ""]
        
        for key, value in config.items():
            if isinstance(value, list):
                lines.append(f"{key}:")
                for item in value:
                    lines.append(f"  - {item}")
            elif isinstance(value, dict):
                lines.append(f"{key}:")
                for k, v in value.items():
                    lines.append(f"  {k}: {v}")
            else:
                lines.append(f"{key}: {value}")
        
        CONFIG_FILE.write_text("\n".join(lines))
        return True
    except Exception as e:
        print_error(f"Failed to write config: {e}")
        return False


# ============================================================================
# Init Wizard
# ============================================================================

def run_init_wizard():
    """Run the interactive installation wizard."""
    print_logo()
    
    console.print(Panel(
        "[bold cyan]Welcome to LastAgent Setup![/]\n\n"
        "This wizard will help you configure LastAgent by:\n"
        "• Checking which agent CLIs are installed\n"
        "• Verifying API key configuration\n"
        "• Setting your default preferences\n",
        title="🔧 Installation Wizard",
        border_style="cyan",
    ))
    console.print()
    
    config = {
        "version": "1.0",
        "default_agent": None,
        "available_agents": [],
        "api_keys_configured": [],
    }
    
    # Step 1: Check installed CLIs
    console.print("[bold]Step 1: Checking installed agent CLIs...[/]\n")
    
    available_agents = []
    for agent, info in SUPPORTED_AGENTS.items():
        installed = check_cli_installed(agent)
        if installed:
            console.print(f"  [green]✓[/] {info['name']} CLI found")
            available_agents.append(agent)
        else:
            console.print(f"  [dim]○[/] {info['name']} CLI not found [dim]({info['url']})[/]")
    
    config["available_agents"] = available_agents
    console.print()
    
    if not available_agents:
        print_warning("No agent CLIs found. Install at least one to use LastAgent.")
        console.print()
        console.print("[dim]Install suggestions:[/]")
        console.print("  • Claude: https://docs.anthropic.com/en/docs/claude-code")
        console.print("  • Gemini: npm install -g @google/gemini-cli")
        console.print("  • Aider:  pip install aider-chat")
        return
    
    # Step 2: Check API keys
    console.print("[bold]Step 2: Checking API key configuration...[/]\n")
    
    configured_keys = []
    for agent in available_agents:
        info = SUPPORTED_AGENTS[agent]
        if info["env_var"]:
            key = check_api_key(agent)
            if key:
                masked = key[:8] + "..." + key[-4:] if len(key) > 12 else "***"
                console.print(f"  [green]✓[/] {info['name']}: {info['env_var']} = {masked}")
                configured_keys.append(agent)
            else:
                console.print(f"  [yellow]○[/] {info['name']}: {info['env_var']} not set")
                console.print(f"      [dim]Get key: {info['url']}[/]")
        else:
            console.print(f"  [green]✓[/] {info['name']}: No API key required")
            configured_keys.append(agent)
    
    config["api_keys_configured"] = configured_keys
    console.print()
    
    # Step 3: Select default agent
    console.print("[bold]Step 3: Select default agent...[/]\n")
    
    if configured_keys:
        default_choices = ", ".join(configured_keys)
        console.print(f"  Available: {default_choices}")
        console.print("  [dim]Or 'auto' to let the council decide[/]\n")
        
        default = Prompt.ask(
            "  Default agent",
            choices=configured_keys + ["auto"],
            default="auto",
        )
        config["default_agent"] = None if default == "auto" else default
    else:
        print_warning("No agents have API keys configured. Using 'auto' mode.")
        config["default_agent"] = None
    
    console.print()
    
    # Step 4: Additional preferences
    console.print("[bold]Step 4: Additional preferences...[/]\n")
    
    yolo_mode = Confirm.ask("  Enable YOLO mode by default? (auto-accept actions)", default=False)
    config["yolo_mode"] = yolo_mode
    
    save_history = Confirm.ask("  Save command history?", default=True)
    config["save_history"] = save_history
    
    console.print()
    
    # Write configuration
    console.print("[bold]Writing configuration...[/]\n")
    
    if write_config(config):
        print_success(f"Configuration saved to {CONFIG_FILE}")
    
    console.print()
    
    # Summary
    console.print(Panel(
        f"[bold green]Setup Complete![/]\n\n"
        f"• Config file: {CONFIG_FILE}\n"
        f"• Available agents: {', '.join(available_agents)}\n"
        f"• Default agent: {config['default_agent'] or 'auto (council decides)'}\n\n"
        f"[dim]Run 'lastagent' to start interactive mode[/]",
        title="✅ Ready to Go",
        border_style="green",
    ))


if __name__ == "__main__":
    run_init_wizard()
